# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seer_lander_ui_speed.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpeedWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 90)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(370, 110, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_DangQian = QtWidgets.QLabel(self.centralwidget)
        self.label_DangQian.setGeometry(QtCore.QRect(60, 20, 30, 12))
        self.label_DangQian.setObjectName("label_DangQian")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(25, 50, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_Bei = QtWidgets.QLabel(self.centralwidget)
        self.label_Bei.setGeometry(QtCore.QRect(150, 20, 21, 12))
        self.label_Bei.setObjectName("label_Bei")
        self.pushButton_QueRen = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_QueRen.setGeometry(QtCore.QRect(210, 15, 75, 25))
        self.pushButton_QueRen.setObjectName("pushButton_QueRen")
        self.pushButton_HuiFu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_HuiFu.setGeometry(QtCore.QRect(210, 50, 75, 25))
        self.pushButton_HuiFu.setObjectName("pushButton_HuiFu")
        self.textEdit_speed = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_speed.setGeometry(QtCore.QRect(95, 13, 50, 25))
        self.textEdit_speed.setObjectName("textEdit_speed")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_DangQian.setText(_translate("MainWindow", "当前："))
        self.label_Bei.setText(_translate("MainWindow", "倍"))
        self.pushButton_QueRen.setText(_translate("MainWindow", "确认"))
        self.pushButton_HuiFu.setText(_translate("MainWindow", "恢复"))
