# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seer_lander_ui_auto.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autoWindow(object):
    def setupUi(self, autoWindow):
        autoWindow.setObjectName("autoWindow")
        autoWindow.resize(350, 70)
        self.centralwidget = QtWidgets.QWidget(autoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GuanQiaQueRen_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.GuanQiaQueRen_pushButton.setGeometry(QtCore.QRect(95, 35, 70, 20))
        self.GuanQiaQueRen_pushButton.setObjectName("GuanQiaQueRen_pushButton")
        self.label_GuanQiaPeiZhi = QtWidgets.QLabel(self.centralwidget)
        self.label_GuanQiaPeiZhi.setGeometry(QtCore.QRect(67, 10, 54, 12))
        self.label_GuanQiaPeiZhi.setObjectName("label_GuanQiaPeiZhi")
        self.label_JingLingPeiZhi = QtWidgets.QLabel(self.centralwidget)
        self.label_JingLingPeiZhi.setGeometry(QtCore.QRect(237, 10, 54, 12))
        self.label_JingLingPeiZhi.setObjectName("label_JingLingPeiZhi")
        self.JingLingQueRen_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.JingLingQueRen_pushButton.setGeometry(QtCore.QRect(265, 35, 70, 20))
        self.JingLingQueRen_pushButton.setObjectName("JingLingQueRen_pushButton")
        self.GuanQiaXuanZe_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.GuanQiaXuanZe_pushButton.setGeometry(QtCore.QRect(15, 35, 70, 20))
        self.GuanQiaXuanZe_pushButton.setObjectName("GuanQiaXuanZe_pushButton")
        self.JingLingXuanZe_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.JingLingXuanZe_pushButton.setGeometry(QtCore.QRect(185, 35, 70, 20))
        self.JingLingXuanZe_pushButton.setObjectName("JingLingXuanZe_pushButton")
        autoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(autoWindow)
        QtCore.QMetaObject.connectSlotsByName(autoWindow)

    def retranslateUi(self, autoWindow):
        _translate = QtCore.QCoreApplication.translate
        autoWindow.setWindowTitle(_translate("autoWindow", "脚本选择"))
        self.GuanQiaQueRen_pushButton.setText(_translate("autoWindow", "确认"))
        self.label_GuanQiaPeiZhi.setText(_translate("autoWindow", "关卡配置"))
        self.label_JingLingPeiZhi.setText(_translate("autoWindow", "精灵配置"))
        self.JingLingQueRen_pushButton.setText(_translate("autoWindow", "确认"))
        self.GuanQiaXuanZe_pushButton.setText(_translate("autoWindow", "选择"))
        self.JingLingXuanZe_pushButton.setText(_translate("autoWindow", "选择"))
