# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seer_lander_ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 560)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 960, 560))
        self.groupBox.setObjectName("groupBox")
        self.axWidget = QAxContainer.QAxWidget(self.groupBox)
        self.axWidget.setGeometry(QtCore.QRect(0, 0, 980, 580))
        self.axWidget.setObjectName("axWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GimTT-SEER-LANDER"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
from PyQt5 import QAxContainer
